defaults:
  - method: full_ft
  - tracker: none
  - _self_

training:
  batch_size: 12
  epochs: 2
  seed: 42
  max_steps: -1
  warmup_ratio: 0.1
  gradient_accumulation_steps: 1
  save_strategy: "no"
  logging_steps: 100
  fp16: true
  dataloader_num_workers: 4

train_size: null  # null means full dataset

output_dir: ${hydra:runtime.output_dir}
